In [38]:
import pandas as pd

from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL
import settings

In [39]:
def db_connect():
    """
    Performs database connection using database settings from settings.py.
    Returns sqlalchemy engine instance
    """
    print URL(**settings.DATABASE)
    return create_engine(URL(**settings.DATABASE))

In [40]:
db = db_connect()

postgres://mimic:thisismetis@metis.cabju7mub8cg.us-west-2.rds.amazonaws.com:5432/MIMIC_ICU

In [53]:
sample = pd.read_sql("""SELECT * FROM chartevents_5 LIMIT 10000;""", db)

In [54]:
sample

,row_id,subject_id,hadm_id,icustay_id,itemid,charttime,storetime,cgid,value,valuenum,valueuom,warning,error,resultstatus,stopped
0,34855631,221,189243.0,247500.0,644,2103-12-18 08:00:00,2103-12-18 09:42:00,21570,Intact,NaN,,None,None,,NotStopd
1,34855632,221,189243.0,247500.0,646,2103-12-18 08:00:00,2103-12-18 08:17:00,17139,99,99.000000,%,None,None,,NotStopd
2,34855633,221,189243.0,247500.0,648,2103-12-18 08:00:00,2103-12-18 08:38:00,21570,Intubated/trach,NaN,,None,None,,NotStopd
3,34855634,221,189243.0,247500.0,655,2103-12-18 08:00:00,2103-12-18 08:38:00,21570,Purposeful,NaN,,None,None,,NotStopd
4,34855635,221,189243.0,247500.0,662,2103-12-18 08:00:00,2103-12-18 08:38:00,21570,57.894699096679688,57.894699,ml,None,None,,NotStopd
5,34855636,221,189243.0,247500.0,663,2103-12-18 08:00:00,2103-12-18 09:42:00,21570,Relative,NaN,,None,None,,NotStopd
6,34855637,221,189243.0,247500.0,664,2103-12-18 08:00:00,2103-12-18 08:38:00,21570,77,77.000000,%,None,None,,NotStopd
7,34855638,221,189243.0,247500.0,674,2103-12-18 08:00:00,2103-12-18 08:38:00,21570,Blood,NaN,,None,None,,NotStopd
8,34855639,221,189243.0,247500.0,677,2103-12-18 08:00:00,2103-12-18 08:38:00,21570,36.388900756835938,36.388901,Deg. C,None,None,,NotStopd
9,34855640,221,189243.0,247500.0,678,2103-12-18 08:00:00,2103-12-18 08:38:00,21570,97.5,97.500000,Deg. F,None,None,,NotStopd
10,34855641,221,189243.0,247500.0,682,2103-12-18 08:00:00,2103-12-18 08:17:00,17139,400,400.000000,ml/B,None,None,,NotStopd
11,34855642,221,189243.0,247500.0,683,2103-12-18 08:00:00,2103-12-18 08:17:00,17139,0,0.000000,ml/B,None,None,,NotStopd
12,34855643,221,189243.0,247500.0,704,2103-12-18 08:00:00,2103-12-18 09:42:00,21570,Back,NaN,,None,None,,NotStopd
13,34855644,221,189243.0,247500.0,707,2103-12-18 08:00:00,2103-12-18 08:38:00,21570,Indwelling Cath,NaN,,None,None,,NotStopd
14,34855645,221,189243.0,247500.0,720,2103-12-18 08:00:00,2103-12-18 08:17:00,17139,CPAP,NaN,,None,None,,NotStopd
15,34855646,221,189243.0,247500.0,721,2103-12-18 08:00:00,2103-12-18 08:17:00,17139,9,9.000000,#,None,None,,NotStopd
16,34855647,221,189243.0,247500.0,722,2103-12-18 08:00:00,2103-12-18 08:17:00,17139,7200A,NaN,,None,None,,NotStopd
17,34855648,221,189243.0,247500.0,723,2103-12-18 08:00:00,2103-12-18 08:38:00,21570,1.0 ET/Trach,1.000000,,None,None,,NotStopd
18,34856693,221,189243.0,247500.0,646,2103-12-19 06:00:00,2103-12-19 06:18:00,21570,99,99.000000,%,None,None,,NotStopd
19,34878135,223,105694.0,255617.0,646,2157-05-12 05:00:00,2157-05-12 04:52:00,15477,97,97.000000,%,None,None,,NotStopd
20,34878149,223,105694.0,255617.0,646,2157-05-12 06:00:00,2157-05-12 06:18:00,15477,99,99.000000,%,None,None,,NotStopd
21,34878165,223,105694.0,255617.0,651,2157-05-12 07:00:00,2157-05-12 07:00:00,21570,,NaN,,None,None,,D/C'd
22,34878166,223,105694.0,255617.0,652,2157-05-12 07:00:00,2157-05-12 07:00:00,21570,,NaN,,None,None,,D/C'd
23,34878167,223,105694.0,255617.0,683,2157-05-12 07:00:00,2157-05-12 07:00:00,21570,,NaN,,None,None,,D/C'd
24,34878168,223,105694.0,255617.0,684,2157-05-12 07:00:00,2157-05-12 07:00:00,21570,,NaN,,None,None,,D/C'd
25,34878169,223,105694.0,255617.0,686,2157-05-12 07:00:00,2157-05-12 07:00:00,21570,,NaN,,None,None,,D/C'd
26,34878170,223,105694.0,255617.0,732,2157-05-12 07:00:00,2157-05-12 07:00:00,21570,,NaN,,None,None,,D/C'd
27,34895432,228,167764.0,235332.0,644,2132-11-04 20:00:00,2132-11-04 20:32:00,17102,Intact,NaN,,None,None,,NotStopd
28,34895433,228,167764.0,235332.0,646,2132-11-04 20:00:00,2132-11-04 20:04:00,18725,100,100.000000,%,None,None,,NotStopd
29,34895434,228,167764.0,235332.0,663,2132-11-04 20:00:00,2132-11-04 20:32:00,17102,Children,NaN,,None,None,,NotStopd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,34668832,175,176764.0,252789.0,707,2184-01-22 19:15:00,2184-01-22 19:33:00,14987,Indwelling Cath,NaN,,None,None,,NotStopd
9971,34668833,175,176764.0,252789.0,722,2184-01-22 19:15:00,2184-01-22 19:33:00,14987,Drager,NaN,,None,None,,NotStopd
9972,34668834,175,176764.0,252789.0,723,2184-01-22 19:15:00,2184-01-22 19:33:00,14987,1.0 ET/Trach,1.000000,,None,None,,NotStopd
9973,34668865,175,176764.0,252789.0,646,2184-01-22 19:37:00,2184-01-22 19:41:00,18725,99,99.000000,%,None,None,,NotStopd
9974,34668866,175,176764.0,252789.0,682,2184-01-22 19:37:00,2184-01-22 19:41:00,18725,463,463.000000,ml/B,None,None,,NotStopd
9975,34668867,175,176764.0,252789.0,683,2184-01-22 19:37:00,2184-01-22 19:41:00,18725,450,450.000000,ml/B,None,None,,NotStopd
9976,34668868,175,176764.0,252789.0,720,2184-01-22 19:37:00,2184-01-22 19:41:00,18725,Assist Control,NaN,,None,None,,NotStopd
9977,34668869,175,176764.0,252789.0,722,2184-01-22 19:37:00,2184-01-22 19:41:00,18725,Drager,NaN,,None,None,,NotStopd
9978,34668870,175,176764.0,252789.0,732,2184-01-22 19:37:00,2184-01-22 19:41:00,18725,RAMP,NaN,,None,None,,NotStopd
9979,34668884,175,176764.0,252789.0,646,2184-01-22 20:00:00,2184-01-22 20:17:00,14987,99,99.000000,%,None,None,,NotStopd
9980,34673124,175,176764.0,252789.0,644,2184-01-27 16:00:00,2184-01-27 17:14:00,15065,Impaired,NaN,,None,None,,NotStopd
9981,34673125,175,176764.0,252789.0,646,2184-01-27 16:00:00,2184-01-27 15:41:00,15796,100,100.000000,%,None,None,,NotStopd
9982,34673126,175,176764.0,252789.0,663,2184-01-27 16:00:00,2184-01-27 17:14:00,15065,Spouse,NaN,,None,None,,NotStopd
9983,34673127,175,176764.0,252789.0,677,2184-01-27 16:00:00,2184-01-27 17:14:00,15065,37.444400787353516,37.444401,Deg. C,None,None,,NotStopd
9984,34673128,175,176764.0,252789.0,678,2184-01-27 16:00:00,2184-01-27 17:14:00,15065,99.400001525878906,99.400002,Deg. F,None,None,,NotStopd
9985,34673129,175,176764.0,252789.0,682,2184-01-27 16:00:00,2184-01-27 15:41:00,15796,527,527.000000,ml/B,None,None,,NotStopd
9986,34673130,175,176764.0,252789.0,683,2184-01-27 16:00:00,2184-01-27 15:41:00,15796,500,500.000000,ml/B,None,None,,NotStopd
9987,34673131,175,176764.0,252789.0,704,2184-01-27 16:00:00,2184-01-27 17:14:00,15065,Left Side,NaN,,None,None,,NotStopd
9988,34673132,175,176764.0,252789.0,707,2184-01-27 16:00:00,2184-01-27 17:14:00,15065,Indwelling Cath,NaN,,None,None,,NotStopd
9989,34673133,175,176764.0,252789.0,720,2184-01-27 16:00:00,2184-01-27 15:41:00,15796,Assist Control,NaN,,None,None,,NotStopd
9990,34673134,175,176764.0,252789.0,722,2184-01-27 16:00:00,2184-01-27 15:41:00,15796,Drager,NaN,,None,None,,NotStopd
9991,34673135,175,176764.0,252789.0,723,2184-01-27 16:00:00,2184-01-27 17:14:00,15065,1.0 ET/Trach,1.000000,,None,None,,NotStopd
9992,34673136,175,176764.0,252789.0,732,2184-01-27 16:00:00,2184-01-27 15:41:00,15796,RAMP,NaN,,None,None,,NotStopd
9993,34673798,175,176764.0,252789.0,644,2184-01-28 08:00:00,2184-01-28 08:35:00,15065,Impaired,NaN,,None,None,,NotStopd
9994,34673799,175,176764.0,252789.0,646,2184-01-28 08:00:00,2184-01-28 08:27:00,18428,100,100.000000,%,None,None,,NotStopd
9995,34673800,175,176764.0,252789.0,674,2184-01-28 08:00:00,2184-01-28 08:35:00,15065,Oral,NaN,,None,None,,NotStopd
9996,34673801,175,176764.0,252789.0,677,2184-01-28 08:00:00,2184-01-28 08:35:00,15065,36.888900756835938,36.888901,Deg. C,None,None,,NotStopd
9997,34673802,175,176764.0,252789.0,678,2184-01-28 08:00:00,2184-01-28 08:35:00,15065,98.400001525878906,98.400002,Deg. F,None,None,,NotStopd
9998,34673803,175,176764.0,252789.0,680,2184-01-28 08:00:00,2184-01-28 08:35:00,15065,AtmosAir Mattres,NaN,,None,None,,NotStopd
9999,34673804,175,176764.0,252789.0,682,2184-01-28 08:00:00,2184-01-28 08:27:00,18428,530,530.000000,ml/B,None,None,,NotStopd

In [ ]:
sample = pd.read_sql("""SELECT * FROM chartevents_5 LIMIT 10000;""", db)

In [43]:
import glob
for filename in glob.glob('E:\Data\MIMIC III\*.csv'):
    #print filename[:-15]
    filename = filename[18:]
    new_file = filename[:-15] + '.csv'
    print 'scp -i c:/.ssh/ssaleh2.pem %s ubuntu@ec2-52-52-69-167.us-west-1.compute.amazonaws.com:~/MIMIC/%s' %(filename, new_file)